openapi: 3.0.3
info:
  title: Maintenance Request Manager
  version: 1.0.0

paths:
  /register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Invalid username or password
  /tickets:
    get:
      operationId: getTickets
      summary: Retrieve all tickets created by the authenticated user
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: List of tickets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketListResponse'

    post:
      operationId: createTicket
      summary: Create a new ticket
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketCreateRequest'
      responses:
        '201':
          description: Ticket created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'

  /tickets/{id}:
    get:
      operationId: getTicket
      summary: Retrieve a single ticket
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ticket details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'

    patch:
      summary: Update or close a ticket
      operationId: updateTicket
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketUpdateRequest'
      responses:
        '200':
          description: Ticket updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'

  /tickets/{id}/attachments:
    post:
      operationId: createAttachment
      summary: Upload attachment to ticket
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ file ]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Attachment uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'

  /tickets/{id}/status:
    patch:
      operationId: updateTicketStatus
      summary: Update the status of a ticket
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketStatusUpdateRequest'
      responses:
        '200':
          description: Ticket status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
        '400':
          description: Invalid status provided
        '404':
          description: Ticket not found

  /tickets/{id}/assign:
    patch:
      operationId: assignTicket
      summary: Assign the ticket to a maintenance worker
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketAssignmentRequest'
      responses:
        200:
          description: Ticket response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
        '400':
          description: Invalid status provided
        '404':
          description: Ticket not found


  /attachments/{attachmentId}:
    get:
      operationId: getAttachment
      summary: Download attachment
      security:
        - bearerAuth: [ ]
      parameters:
        - name: attachmentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: File stream
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid attachment
        '404':
          description: Ticket not found


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthenticationRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: john.doe
        password:
          type: string
          format: password
          example: myPassword123

    RegisterRequest:
      type: object
      required:
        - firstName
        - lastName
        - username
        - email
        - password
        - role
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john.doe@example.com
        password:
          type: string
          format: password
          example: MySecurePassword123
        addressLine:
          type: string
          example: Main Street
        addressLine2:
          type: string
          example: Building A
        buildingNr:
          type: integer
          example: 15
        apartmentNr:
          type: integer
          example: 7
        role:
          $ref: '#/components/schemas/Role'

    Role:
      type: string
      enum:
        - USER
        - WORKER
        - ADMIN

    AuthenticationResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWT access token
          example: eyJhbGciOiJIUzI1NiJ9...

    TicketCreateRequest:
      type: object
      required:
        - title
        - description
        - category
        - type
      properties:
        title:
          type: string
        description:
          type: string
        category:
          $ref: '#/components/schemas/TicketCategory'
        type:
          $ref: '#/components/schemas/TicketType'

    TicketStatusUpdateRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/TicketStatus'

    TicketUpdateRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        category:
          $ref: '#/components/schemas/TicketCategory'
        type:
          $ref: '#/components/schemas/TicketType'

    TicketUpdatePriorityRequest:
      type: object
      required:
        - priority
      properties:
        priority:
          $ref: '#/components/schemas/TicketPriority'

    TicketAssignmentRequest:
      type: object
      required:
        - assignedUserId
      properties:
        assignedUserId:
          type: integer
          format: int64

    TicketResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        category:
          $ref: '#/components/schemas/TicketCategory'
        type:
          $ref: '#/components/schemas/TicketType'
        status:
          $ref: '#/components/schemas/TicketStatus'
        priority:
          $ref: '#/components/schemas/TicketPriority'
        createdAt:
          type: string
          format: date-time

    TicketCategory:
      type: string
      enum:
        - PLUMBING
        - ELECTRICAL
        - HVAC
        - CARPENTRY
        - APPLIANCE
        - CLEANING
        - OTHER

    TicketType:
      type: string
      enum:
        - WATER_LEAK
        - CLOGGED_DRAIN
        - HEATING_FAILURE
        - POWER_OUTAGE
        - LIGHT_FIXTURE
        - BROKEN_WINDOW
        - BROKEN_DOOR
        - APPLIANCE_REPAIR
        - CLEANING_REQUEST
        - OTHER

    AttachmentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        filename:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
        uploadedAt:
          type: string
          format: date-time

    TicketStatus:
      type: string
      enum:
        - OPEN
        - ASSIGNED
        - IN_PROGRESS
        - COMPLETED
        - CANCELLED

    TicketPriority:
      type: string
      enum:
        - LOW
        - MEDIUM
        - HIGH
        - URGENT

    TicketListResponse:
      type: array
      items:
        $ref: '#/components/schemas/TicketResponse'

    WorkerCreateRequest:
      type: object
      required:
        - firstName
        - lastName
        - username
        - email
        - password
      properties:
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password

security:
  - bearerAuth: []


