spring:
  application:
    name: Maintenance_request_manager
  datasource:
    url: jdbc:postgresql://localhost:5432/maintenance_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
