spring:
  application:
    name: Maintenance_request_manager
  datasource:
    url: jdbc:postgresql://localhost:5432/maintenance_db
    username: ${DB+USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

app:
  file-storage:
    max-size=10485760:
    path: uploads