openapi: 3.0.3
info:
  title: Maintenance Request Manager
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TicketCreateRequest:
      type: object
      required: [title, description]
      properties:
        title:
          type: string
        description:
          type: string

    TicketResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time

security:
  - bearerAuth: []


paths:
  /ticket:
    post:
      summary: Create a new ticket
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketCreateRequest'
      responses:
        '201':
          description: Ticket created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
